var annotated_dup =
[
    [ "BinaryNode", "class_binary_node.html", "class_binary_node" ],
    [ "BST", "class_b_s_t.html", "class_b_s_t" ],
    [ "BSTItrIn", "class_b_s_t_itr_in.html", "class_b_s_t_itr_in" ],
    [ "BSTItrLevel", "class_b_s_t_itr_level.html", "class_b_s_t_itr_level" ],
    [ "BSTItrPost", "class_b_s_t_itr_post.html", "class_b_s_t_itr_post" ],
    [ "BSTItrPre", "class_b_s_t_itr_pre.html", "class_b_s_t_itr_pre" ],
    [ "Club", "class_club.html", "class_club" ],
    [ "Date", "class_date.html", "class_date" ],
    [ "DuplicateName", "class_duplicate_name.html", "class_duplicate_name" ],
    [ "Event", "class_event.html", "class_event" ],
    [ "hashFuncs", "structhash_funcs.html", "structhash_funcs" ],
    [ "InvalidDate", "class_invalid_date.html", "class_invalid_date" ],
    [ "InvalidPlayer", "class_invalid_player.html", "class_invalid_player" ],
    [ "Juniors", "class_juniors.html", "class_juniors" ],
    [ "Juveniles", "class_juveniles.html", "class_juveniles" ],
    [ "Level", "class_level.html", "class_level" ],
    [ "Minis", "class_minis.html", "class_minis" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "Player_node", "struct_player__node.html", "struct_player__node" ],
    [ "Player_queue", "struct_player__queue.html", "struct_player__queue" ],
    [ "Seniors", "class_seniors.html", "class_seniors" ],
    [ "Tournament", "class_tournament.html", "class_tournament" ],
    [ "Training", "class_training.html", "class_training" ]
];